### ISSUE TITLE
Any word

### ISSUE THREAD

**Issue by howna13** [codingforentrepreneurs/Guides#5]
Hello! Those guides are very useful. I found myself trying to find the regular expression that matches really any word so that anything that you write will be send to another url dispatcher.

**Comment by codingforentrepreneurs** [comment]
Hi there, maybe you should consider learning more about Python Regex? We have a tutorial for it here: https://www.codingforentrepreneurs.com/projects/python-regex/

Learning regex will definitely help you solve the issue you're trying to do. Combine that with the Django Redirect View and I think you will find your solution. 

Good luck!
